name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check application import
        run: python -c "import app.main"

      - name: Build docker image
        run: docker build -t devops-task-api:ci .

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Lint Helm chart
        run: helm lint ./task-api --set db.password=ci-test-password
